config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'
  resources :pets, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  include ActionView::Helpers::TextHelper
  validates :animal, presence: true
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
# require "open-uri"
# require "nokogiri"
  def index
    @pagy, @pets = pagy(Pet.all.order(created_at: :desc))
  end

  def show
  end

  @all_pets = []

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Japan Pets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pets/_pagination.html.erb
<div class="pages__pets">
  <div class="d-flex">
    <p class="mr-2">Results per page: </p>
    <div>
      <%= link_to_unless_current "10", pets_path(items: 10) %>
      <%= link_to_unless_current "20", pets_path(items: 20) %>
      <%= link_to_unless_current "50", pets_path(items: 50) %>
      <%= link_to_unless_current "100", pets_path(items: 100) %>
    </div>
  </div>
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/pets/_pet-list.html.erb
<div class="container__pets mb-3">
  <% @pets.each do |pet| %>
    <div class="pet-container">
      <% if pet.photo.attached? %>
        <%= image_tag(pet.photo) %>
      <% end %>
      <div class="pet-container-infos">
        <% if pet.name != nil %>
          <% if pet.name.length > 1 %>
            <h3><%= pet.name.split(" ").first %></h3>
          <% else %>
            <h2><%= pet.name %></h2>
          <% end %>
        <% end %>
        <% if pet.animal != nil && pet.gender.present?%>
          <p class="animal"><%= pet.animal.capitalize %> | <%= pet.gender.capitalize %></p>
        <% else %>
          <p class="animal"><%= pet.animal.capitalize %></p>
        <% end %>
        <% if pet.age != nil %>
          <p><%= pet.age %></p>
        <% end %>
        <% if pet.breed != nil %>
          <p><%= pet.breed %></p>
        <% end %>
        <% if pet.description != nil && pet.description.length > 5 %>
          <% if pet.description.include?("a" || "the" || "an") %>
            <p><%= pet.description.first(200) %>...</p>
          <% else %>
            <p><%= pet.description.first(50) %>...</p>
          <% end %>
        <% end %>
        <% if pet.url.present? %>
          <%= link_to pet.url, target:"_blank" do %>
            <p>Click here for more info</p>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pets/_search.html.erb
<% animals = [] %>
<% Pet.all.each do |pet| %>
  <% animals << pet.animal.capitalize unless animals.include?(pet.animal.capitalize) %>
<%  end %>
<div class="search-box">
  <h4>Search by location and/or animal</h4>
  <%# removing location for now, maybe we can add it later %>
  <%# <label>Location</label>
  <input class="search-box-inputs" type="text" id="location" placeholder="Ex: Tokyo" /> %>
  <label>Animal</label>
  <select class="search-box-inputs" id="animal">
    <option />
    <% animals.each do |animal| %>
      <option><%= "#{animal}" %></option>
    <% end %>
  </select>
  <button class="submit">Submit</button>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h1>Japan Pets</h1>
  <div class="d-flex my-4">
    <%= render 'search' %>
    <h3 class="mx-3">Adopting a pet is a wonderful thing. But if you live in Japan and don't speak Japanese well enough, it can be difficult finding the right pet for you on the various websites available. Japan Pets aims to fix that. We've scoured the web and found as many pets available for adoption in Japan and put them all on our site. We don't take care of the pets. We only compile a list of them. For more information, please click on the link and you'll be redirected to the site hosting the pet. Japan Pets was created by and is maintained by volunteers.</h3>
  </div>
  <%= render 'pagination' %>
  <%# <h3 class="my-3"> Pets Found </h3> %>
  <%= render 'pet-list' %>
  <%= render 'pagination' %>
</div>